name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: SSH EC2login
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          script:
            # pwd:
            cd /home/ubuntu/2025memberdev
            git config --global --add safe.directory /home/ubuntu/2025memberdev
            sudo git pull origin main
            sudo ./gradlew clean bootWar
            sudo fuser -k -n tcp 8080
            sudo nohup java -jar build/libs/*SNAPSHOT.war > /dev/null 2>&1 &
