name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: SSH EC2login
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          script:
          pwd:
