name: github action test

on:
  push: # {branch:main}
    branches:
      - main #event

jobs:
  My-Deploy-Job: #임의로 이름지은 것
    runs-on: ubuntu-latest
    steps:
      - name: Hello 찍기 #testing
        run: echo "Hello World"
      - name: 여러 명령어 넣기
        run: |
          echo "good"     #echo = console.log같은 기능
          echo "morning"

      - name: 변수사용
        run: |
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY

      - name: 비밀 변수사용
        run: |
          echo ${{ secrets.MY_NAME}}   
          echo ${{ secrets.MY_HOBBY}}
