name: github action test

on:
  push: # {branch:main}
    branches:
      - main #event

jobs:
  My-Deploy-Job: #임의로 이름지은 것
    runs-on: ubuntu-latest
    steps:
      - name: Hello 찍기 #testing
        run: echo "Hello World"
